name: "Publish library to GitHub Packages"
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        env:
          USERNAME: SorrowBlue
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew twitlin:publish
        
      - name: Publish
        uses: actions/create-release@master
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # リリースのタグ (必須)
          tag_name: ${{ github.ref }}
          # リリースのタイトル (必須)
          release_name: First Release 0.0.1-dev-001
          # リリースのタイトル (省略可能)
          body: |
            # Twitlin First Release
            Twitlin is a wrapper library for the Twitter API.<br />
            I am happy to be able to publish it.<br />
            **Not all features are implemented in this version yet.**
          # 下書き状態で作成する場合は true (省略時 false)
          draft: false
          # プレリリース表示を付ける場合は true (省略時 false)
          prerelease: true
