name: Publish library to GitHub Packages

on: push

jobs:
  build:
    name: publish snapshot
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
      "ORG_GRADLE_PROJECT_signing.keyId": ${{ secrets.SIGNING_KEY_ID }}
      "ORG_GRADLE_PROJECT_signing\\.keyId": ${{ secrets.SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signing\\.keyId: ${{ secrets.SIGNING_KEY_ID }}
      "ORG_GRADLE_PROJECT_signing.password": ${{ secrets.SIGNING_PASSWORD }}
      "ORG_GRADLE_PROJECT_signing.secretKeyRingFile": ${{ steps.write_file.outputs.filePath }}
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_sonatypeStagingProfileId: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: generate pgp
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}'
          encodedString: ${{ secrets.SORROW_BLUE_XXXXXXXX_SECRET }}
      - name: Build with Gradle
        run: ./gradlew twitlin:publish
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: twitlin-ci
          SLACK_TITLE: Success publish release
          SLACK_COLOR: good
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: twitlin-ci
          SLACK_TITLE: Failure publish release
          SLACK_COLOR: danger
