name: Publish library to GitHub Packages

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: publish snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeStagingProfileId: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
        run: ./gradlew :twitlin:publishAllPublicationsToGitHubPackagesRepository :twitlin:publishToSonatype :twitlin:closeAndReleaseSonatypeStagingRepository

      - name: Slack Notification on Success
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TWITLIN_CI }}
        with:
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "${{ github.event.head_commit.message }}",
                  "emoji": true
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "plain_text",
                    "text": ":white_check_mark: ${{ github.workflow }} #${{ github.run_number }}"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "image",
                    "image_url": "${{ github.event.sender.avatar_url }}",
                    "alt_text": "Avatar url"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "${{ github.event.sender.login }} _${{ github.event_name }}_ :link:${{ steps.short-sha.outputs.sha }} *${{ env.BRANCH_NAME }}*"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Status*\nSuccess"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Workflow",
                      "emoji": true
                    },
                    "value": "workflow",
                    "url": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}",
                    "action_id": "workflow"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Commit",
                      "emoji": true
                    },
                    "value": "commit",
                    "url": "${{ github.event.head_commit.url }}",
                    "action_id": "commit"
                  }
                ]
              }
            ]

      - name: Slack Notification on Failure
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TWITLIN_CI }}
        with:
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "${{ github.event.head_commit.message }}",
                  "emoji": true
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "plain_text",
                    "text": ":white_check_mark: ${{ github.workflow }} #${{ github.run_number }}"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "image",
                    "image_url": "${{ github.event.sender.avatar_url }}",
                    "alt_text": "Avatar url"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "${{ github.event.sender.login }} _${{ github.event_name }}_ :link:${{ steps.short-sha.outputs.sha }} *${{ env.BRANCH_NAME }}*"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Status*\nFailure"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Workflow",
                      "emoji": true
                    },
                    "value": "workflow",
                    "url": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}",
                    "action_id": "workflow"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Commit",
                      "emoji": true
                    },
                    "value": "commit",
                    "url": "${{ github.event.head_commit.url }}",
                    "action_id": "commit"
                  }
                ]
              }
            ]
