name: "Publish library to GitHub Packages"
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: publish snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: generate pgp
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}'
          encodedString: ${{ secrets.SORROW_BLUE_XXXXXXXX_SECRET }}
      - name: Build with Gradle
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ steps.write_file.outputs.filePath }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        run: ./gradlew twitlin:publish
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: twitlin-ci
          SLACK_TITLE: Success publish release
          SLACK_COLOR: good
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: twitlin-ci
          SLACK_TITLE: Failure publish release
          SLACK_COLOR: danger
